### ISSUE TITLE
illegible font on Windows/Chrome

### ISSUE THREAD

**Issue by HiroAgustin** [segment-boneyard/myth.io#2]
Font looks crisp and too thin to read

![screenshot](https://drive.google.com/file/d/0B23Wp-yaoFzFNzEzZjRpSnFiNTQ/edit?usp=sharing)

**Comment by ianstormtaylor** [comment]
hmm i guess the only solution is literally doing an OS check? :/

**Comment by pjkix** [comment]
most likely due to missing font hinting for windows, i just dealt with a similar issue here's a good overview http://www.smashingmagazine.com/2012/04/24/a-closer-look-at-font-rendering/
more here http://blog.webink.com/why-fonts-suck-windows-hinting/

**Comment by bluesix** [comment]
![myth_fonts](https://f.cloud.github.com/assets/195220/1787181/28492bbe-6901-11e3-8417-5e51f2ee34ac.png)
Ditto - screenshot attached Win7/Chrome31

**Comment by jennschiffer** [comment]
The latest merge solves this issue: Win7/Chrome31:
![fixedissue](https://f.cloud.github.com/assets/341305/1803622/2d8660ae-6c23-11e3-8b93-74e71d63ebb6.jpg)
